question_list = [
  "When is your birthday?",
  "What is your favorite color?",
  "Do you have a driver's license?",
  "What is your favorite color?",
  "Are you a neat or a messy person?",
  "Do you have any pets?",
  "What is your favorite dessert?",
  "What is your favorite drink?",
  "Are you a party person?",
  "What is your biggest fear?",
  "Do you have any pet peeves?",
  "When do you usually sleep and wake during weekdays?",
  "When do you usually sleep and wake during weekends?",
  "Are you a morning or night person?",
  "Which city or county are you from?",
  "What is your major?",
  "What do you want to do in the future?",
  "Are you more of an introvert or an extrovert?",
  "Do you play any sports?",
  "Do you play any instruments?",
  "What is your favorite season and why?",
  "What are some of your hobbies?",
  "What are you most looking forward to in college?",
  "Do you play any video games? If yes, what are some of your favorite games?",
  "What kind of music do you like to listen to?",
  "How often do you plan to go home?",
  "What other language do you speak, if any?",
  "Where do you like to study?",
  "Do you smoke or use alcohol?",
  "Are you an optimistic or a pessimistic person?",
  "What is your favorite ice cream flavor?",
  "What is your Instagram handle?",
  "What is your phone number?",
  "Do you have any siblings?",
  "What is your pronoun?",
  "Are you currently working?",
  "Do you plan to find an on-campus job?",
  "If there is a disagreement, what approach do you feel is best for working through it?",
  "How do you feel about overnight guests?",
  "Do you collect anything?"
]